# Generated by Django 3.0.4 on 2020-03-18 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campNowProjects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='owner',
        ),
    ]
